# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: Graphite
    orgId: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: prometheus
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    orgId: 1
    jsonData:
      httpMethod: POST
      manageAlerts: true
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
  - name: influxdb
    type: influxdb
    access: proxy
    user: telegraf
    orgId: 1
    url: http://influxdb:8086
    isDefault: true